services:
  frontend:
    build:
      context: ./snapmap-frontend
      target: dev
    ports:
      - "5173:5173"
    env_file:
      - ./snapmap-frontend/.env
    depends_on:
      - api

  api:
    build:
      context: ./snapmap-backend
      args:
        APP_ENV: dev
    ports:
      - "8000:8000"
    env_file:
      - ./snapmap-backend/.env
    environment:
      MONGODB_URI: mongodb://mongo:27017/?directConnection=true
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
