services:
  frontend:
    build:
      context: ./snapmap-frontend
      target: prod
    ports:
      - "4173:4173"
    depends_on:
      - api

  api:
    build:
      context: ./snapmap-backend
      args:
        APP_ENV: prod
    ports:
      - "8000:8000"
    env_file:
      - ./snapmap-backend/.env.prod
